# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from parent_wire import schema_pb2 as parent__wire_dot_schema__pb2


class ParentStub(object):
    """The service running in the background that organizes our machines
    so that they can easily communicate without having to hardcode things
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ImAlive = channel.unary_unary(
                '/clock_model.Parent/ImAlive',
                request_serializer=parent__wire_dot_schema__pb2.ImAliveRequest.SerializeToString,
                response_deserializer=parent__wire_dot_schema__pb2.BirthResponse.FromString,
                )
        self.ImDying = channel.unary_unary(
                '/clock_model.Parent/ImDying',
                request_serializer=parent__wire_dot_schema__pb2.Identity.SerializeToString,
                response_deserializer=parent__wire_dot_schema__pb2.DeathResponse.FromString,
                )


class ParentServicer(object):
    """The service running in the background that organizes our machines
    so that they can easily communicate without having to hardcode things
    """

    def ImAlive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImDying(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ImAlive': grpc.unary_unary_rpc_method_handler(
                    servicer.ImAlive,
                    request_deserializer=parent__wire_dot_schema__pb2.ImAliveRequest.FromString,
                    response_serializer=parent__wire_dot_schema__pb2.BirthResponse.SerializeToString,
            ),
            'ImDying': grpc.unary_unary_rpc_method_handler(
                    servicer.ImDying,
                    request_deserializer=parent__wire_dot_schema__pb2.Identity.FromString,
                    response_serializer=parent__wire_dot_schema__pb2.DeathResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clock_model.Parent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Parent(object):
    """The service running in the background that organizes our machines
    so that they can easily communicate without having to hardcode things
    """

    @staticmethod
    def ImAlive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clock_model.Parent/ImAlive',
            parent__wire_dot_schema__pb2.ImAliveRequest.SerializeToString,
            parent__wire_dot_schema__pb2.BirthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ImDying(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clock_model.Parent/ImDying',
            parent__wire_dot_schema__pb2.Identity.SerializeToString,
            parent__wire_dot_schema__pb2.DeathResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
