# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parent_wire/schema.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18parent_wire/schema.proto\x12\x0b\x63lock_model\"\x10\n\x0eImAliveRequest\"&\n\x08Identity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\"\x98\x01\n\rBirthResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12,\n\x08identity\x18\x03 \x01(\x0b\x32\x15.clock_model.IdentityH\x00\x88\x01\x01\x12$\n\x05peers\x18\x04 \x03(\x0b\x32\x15.clock_model.IdentityB\x0b\n\t_identity\"\x0f\n\rDeathResponse2\x8a\x01\n\x06Parent\x12\x42\n\x07ImAlive\x12\x1b.clock_model.ImAliveRequest\x1a\x1a.clock_model.BirthResponse\x12<\n\x07ImDying\x12\x15.clock_model.Identity\x1a\x1a.clock_model.DeathResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'parent_wire.schema_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMALIVEREQUEST._serialized_start=41
  _IMALIVEREQUEST._serialized_end=57
  _IDENTITY._serialized_start=59
  _IDENTITY._serialized_end=97
  _BIRTHRESPONSE._serialized_start=100
  _BIRTHRESPONSE._serialized_end=252
  _DEATHRESPONSE._serialized_start=254
  _DEATHRESPONSE._serialized_end=269
  _PARENT._serialized_start=272
  _PARENT._serialized_end=410
# @@protoc_insertion_point(module_scope)
